### ISSUE TITLE
Tag versions on Docker Hub

### ISSUE THREAD

**Issue by verwilst** [phpdocker-io/base-images#10]
Currently there's only a 'latest' tag on hub.docker.com. Would it be possible to tag actual versions for php as well?

**Comment by luispabon** [comment]
You mean as in `phpdockerio/php71-fpm:7.1.1-whatever`? Unfortunately not at this time, as we're using Docker hub's build system and have no control over it. It will tag everything as latest. We would need to host and switch our own buid system to get that level of control.

I will investigate alternatives though, I can see where you're coming from. You're having to force a docker pull to get updates, yes?

**Comment by verwilst** [comment]
Wow, time flies! Totally forgotten this post, and didn't answer, my apologies! If you don't have access or not enough funds to get your own buildserver, I might be able to help out?

**Comment by dmitryuk** [comment]
The composer 2 ruined our local docker stack

**Comment by luispabon** [comment]
To be fair composer 2 could've only ruined your setup if your app wasn't correctly set up in the first place. Bit of technical debt you didn't know you have there.

**Comment by dmitryuk** [comment]
We had hirak/prestissimo package installed locally, but it requires composer v1
