### ISSUE TITLE
[php71-fpm] Connection refused

### ISSUE THREAD

**Issue by yosmanyga** [phpdocker-io/base-images#14]
I get a "111: Connection refused" when using a phpdockerio/php71-fpm container and try to access from a nginx container. But it gets fixed if I restart the php7.1-fpm service.

**Comment by luispabon** [comment]
Are you using it as part of a phpdocker.io generated environment?

**Comment by yosmanyga** [comment]
No, I'm using php71-fpm independently.

**Comment by luispabon** [comment]
:+1: what I gather is happening is nginx is coming fully online before fpm does. This in itself shouldn't be an issue:
  * A solution is to ensure fpm comes online before you fire up fpm, on docker-compose (if that's what you're using) you can do this by judicious use of container ordering and links
  * The better solution is to configure nginx to retry a given backend:

```
    upstream php-fpm {
        server php-fpm:9000 max_fails=3;
    }
```

**Comment by yosmanyga** [comment]
Looks like it's my own problem on entrypoint configuration. Thanks anyway for your support.
