### ISSUE TITLE
Locale is missing

### ISSUE THREAD

**Issue by madbbb** [phpdocker-io/base-images#16]
I use your dockerfile which was made from phpdockerio/php71-fpm:latest image. It doesn't have any locale configuration and by default locale is POSIX. Without proper locale many multibyte php functions such basename work not properly. I don't know if it is an issue, but setting default locale to UTF-8 helped me a lot.

You could add lines this to your docker file to set it.

RUN apt-get update \
    && apt-get -y --no-install-recommends install **locales** php7.1-mysql php7.1-intl php7.1-mbstring php7.1-sqlite3\
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

**Comment by luispabon** [comment]
Not adding in a default locale beyond what Ubuntu itself offers on their base image is done on purpose to avoid biasing towards being country-specific - while ~8% of phpdocker.io users are indeed from the US, India is 6%, Russia and Ukraine combined are 9%, you get the idea.

I know it's not the answer you'd like to hear, but it's each user's responsibility to customise their set up to their locale.
