### ISSUE TITLE
Using phpdockerio/php72-fpm with nginx on the server

### ISSUE THREAD

**Issue by heihachi88** [phpdocker-io/base-images#19]
Launched container:

```
docker run -d --restart always phpdockerio/php72-fpm -p 9090:9000
```

Here's nginx config (nginx installed on the local machine without docker containers):

```
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass localhost:9090;
        fastcgi_index index.php;
        include fastcgi.conf;
    }
```

But nginx throws 404 not found errors in a log. What i am doing wrong?

**Comment by luispabon** [comment]
You aren't providing your application code to the php-fpm container. Generate a docker-compose environment at https://phpdocker.io and see how it works.
