### ISSUE TITLE
MySQL, could not find driver

### ISSUE THREAD

**Issue by mvaljento** [phpdocker-io/base-images#21]
After building today from phpdockerio/php72-fpm:latest, my MySQL drivers stopped working when deploying on my stack. Everything seems to work locally in my Mac, though.

I'm new to Docker, so not sure if I've missed something. Any help appreciated.

**Comment by mvaljento** [comment]
Seems to be working again after the latest build.

**Comment by luispabon** [comment]
mmm bizarre. It's possible the mysql package failed to install, or it's possible there was momentarily a dodgy version of the driver on the repositories. Glad it's fixed tho :+1:
