### ISSUE TITLE
[php56-fpm] fails due to jessie packages moving to archive.debian.org

### ISSUE THREAD

**Issue by Komorebi-E** [phpdocker-io/base-images#23]
Debian have moved the jessie pacakages to `archive.debian.org` so the sources.list needs updating to prevent the following build error:

### Build error

`FROM phpdockerio/php56-fpm:latest`

```
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
Fetched 10.1 MB in 8s (1250 kB/s)
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get update     && apt-get -y --no-install-recommends install php5-mysql wget php5-xdebug php5-gd php5-intl' returned a
non-zero code: 100
```

### Cause

[Debian announce list](https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html)

> Removal of Wheezy and Jessie (except LTS) from mirrors

> Hello,
> 
> as Wheezy and Jessie have been integrated into the archive.debian.org
> structure recently, we are now removing all of Wheezy and all non-LTS
> architectures of Jessie from the mirror network starting today.
> That is, only Jessie i386, amd64, armel and armhf will continue to be
> hosted on the normal mirrors.
> 
> The data is, of course, not lost - the whole of it is synced
> to archive.debian.org, so if you still need it you will be able to get
> it from there.[1]
> 
> [1] Keep in mind that they have no security support at all!
> --
> bye, Joerg

### Possible solution

[Stack Exchange comment](https://unix.stackexchange.com/a/508728)

**Comment by luispabon** [comment]
Thank you for the report, I'll fix this right away

**Comment by luispabon** [comment]
@Komorebi-E could you please pull the image and try again?

**Comment by johannesdr-tb** [comment]
Hi @luispabon. I work with @Komorebi-E. 
It looks like the image is working again, thanks for the quick fix.

**Comment by luispabon** [comment]
No worries, thanks for reporting it :+1:
