### ISSUE TITLE
Latest version of php71-fpm no longer includes git (incompatible with previous versions)

### ISSUE THREAD

**Issue by reneheijnemans** [phpdocker-io/base-images#32]
Commit c2ce212bbe8df28d4be28b8a164d3f8365dff244 removed `git` from the apt-get installation
I am not sure this was intended? However this breaks my images as those depend on `git`.

**Comment by luispabon** [comment]
Apologies this broke your setup. This was an intended change, git was never supposed to be in the base images and the 7.1 image was an outlier having it (none of the other base images have it). It can be added on the generator at https://phpdocker.io/generator. You can simply apt install git on your Dockerfiles instead.
