### ISSUE TITLE
PHP 7.3 missing in docker.io registry

### ISSUE THREAD

**Issue by fwg** [phpdocker-io/base-images#50]
Somehow there are no 7.3 images up on docker hub: https://hub.docker.com/r/phpdockerio/php/tags?page=1&name=7.3

I would like to be able to use `FROM phpdockerio/php:7.3-fpm` in my `Dockerfile` 😉

**Comment by luispabon** [comment]
The php repository is actually very new, from the last few months. It only
contains the currently supported versions of PHP, which starts with 7.4.

Before there were separate repositories depending on the version. If you
look at the readme on this repo, it'll tell you what to use for 7.3.
