### ISSUE TITLE
PHP 8.* installed on php7.4 and php5.6 image versions

### ISSUE THREAD

**Issue by luispaulotoniettefranca** [phpdocker-io/base-images#51]
On using php7.4 or php5.6 images and run `php -v` command, this is the result:

![image](https://user-images.githubusercontent.com/12602917/150807566-104bac65-b133-49e7-add7-54f32c165d10.png)

How can I change the default PHP version to 7.4 or 5.6 instead of 8.*?

I did captured this "error" running `composer install` and receiving platform incompatibilities messages.

**Comment by luispabon** [comment]
Are you using the image via a dockerfile? If so, paste it here please.

**Comment by luispaulotoniettefranca** [comment]
I'm composing 4 similar Dockerfiles with your images and receiving the same error in both

**Comment by luispabon** [comment]
Try installing php7.4-mongodb instead of php-mongodb

**Comment by luispabon** [comment]
Yes, that's exactly the problem:

![image](https://user-images.githubusercontent.com/6388823/150986969-2df5dd9f-d428-4ee8-becb-f4156d7d186e.png)

closing.
