### ISSUE TITLE
gd not working with php74-fpm

### ISSUE THREAD

**Issue by dan-willett** [phpdocker-io/base-images#55]
I installed gd in the php74-fpm docker

When I do:  php -m 
it shows as being installed.   I created a test file test.php and when I run it from the shell using php ./test.php it shows gd as being installed, but when I do the same test in the file that I am serving the fpm using Nginx the test shows that gd is not installed...

```php
if (!function_exists('imagecreatetruecolor')) echo "it isn't here/n";
if (function_exists('imagecreatetruecolor')) echo "Here it is!/n";
```

Why is that?  What do I need to do to get gd to be installed when going through fpm?

**Comment by dan-willett** [comment]
Never mind, I re-pulled the image, installed gd and restarted the container and it started working correctly, not sure, it may have been an issue with an older image, but the current image is working correctly...

**Comment by luispabon** [comment]
👍🏽
