### ISSUE TITLE
PHP 4.3.8?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [phpdocker-io/base-images#58]
Is it possible to request a base image be built?

Reason: I have a very old website that we all used to use made with PHPNuke and it uses 4.3.8.

I'm having the worst time trying to get an image with that version in it, or to make one myself (I have very little linux experience, and have also never created a dockerfile myself). I was hoping the wizards here would be able to whip one up easily that I could then do the rest myself (i.e. add nginx to serve the site, and connect to a mariadb).

Thanks!
Kacey

**Comment by luispabon** [comment]
Unfortunately the philosophy here is to slowly deprecate earlier versions of PHP to avoid promoting the use of them, which has blighted the PHP ecosystem for years.

I have however found this one on docker hub for php 4.4 that perhaps could do the trick for you:

https://hub.docker.com/r/nouphet/docker-php4/
