### ISSUE TITLE
docker pull 

### ISSUE THREAD

**Issue by ahpetrot** [phpdocker-io/base-images#9]
Issue doing a pull.

Thoughts? 

--------------------------

docker pull phpdockerio/nginx
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/info: open //./pipe/docker_engine: The system cannot find the file specified.). Using system default: https://index.docker.io/v1/
An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/images/create?fromImage=phpdockerio%2Fnginx%3Alatest: open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by luispabon** [comment]
Closing as I cannot reproduce this and no more feedback has been received.
